/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;

/**
 *
 * @author Kevin
 */
public class Agregar_Productos extends javax.swing.JFrame
  {

    /**
     * Creates new form Agregar_Productos
     */
    public Agregar_Productos()
      {
        initComponents();
        CtrlInterfaz.limpia(jtNombre, jtCompra, jtFCad, jtFVenta, jtMarca, jtProveedor, jtVenta);
        CtrlInterfaz.habilita(false, btnAceptar, btnBuscar, jtVenta, jtCompra, jtFCad, jtFVenta, jtMarca, jtProveedor, jcPerec);
        jcPerec.setEnabled(false);
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcPerec = new javax.swing.JCheckBox();
        jtNombre = new javax.swing.JTextField();
        jtMarca = new javax.swing.JTextField();
        jtCompra = new javax.swing.JTextField();
        jtVenta = new javax.swing.JTextField();
        jtProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtFCad = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jtFVenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Marca");

        jLabel3.setText("$Compra");

        jLabel4.setText("$Venta");

        jLabel5.setText("Proveedor");

        jcPerec.setText("Perecedero");
        jcPerec.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcPerecActionPerformed(evt);
            }
        });

        jtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtNombreKeyTyped(evt);
            }
        });

        jtMarca.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtMarcaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtMarcaKeyTyped(evt);
            }
        });

        jtCompra.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtCompraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtCompraKeyTyped(evt);
            }
        });

        jtVenta.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtVentaKeyTyped(evt);
            }
        });

        jtProveedor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtProveedorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtProveedorKeyTyped(evt);
            }
        });

        jLabel6.setText("Fecha de Caducidad");
        jLabel6.setEnabled(false);

        jtFCad.setText("DD/MM/AAAA");
        jtFCad.setEnabled(false);
        jtFCad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtFCadActionPerformed(evt);
            }
        });
        jtFCad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtFCadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtFCadKeyTyped(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantidad", "Peso" }));

        jLabel7.setText("Forma de venta");

        jtFVenta.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtFVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtFVentaKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcPerec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtFCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(jtNombre)
                                .addComponent(jtMarca)
                                .addComponent(jtCompra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtFVenta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addComponent(jtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcPerec)
                    .addComponent(jLabel6)
                    .addComponent(jtFCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtFVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtFCadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtFCadActionPerformed
    {//GEN-HEADEREND:event_jtFCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFCadActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed

        String nombre = jtNombre.getText();
        String marca = jtMarca.getText();
        int compra = Integer.parseInt(String.valueOf(jtCompra));
        int venta = Integer.parseInt(String.valueOf(jtVenta));
        String proveedor = jtProveedor.getText();
        String fVenta = jtFVenta.getText();


    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNombreKeyPressed
    {//GEN-HEADEREND:event_jtNombreKeyPressed
        if (jtNombre.getText().isEmpty() != true)
          {
            Validaciones.enter(this, evt, jtMarca);
          }
    }//GEN-LAST:event_jtNombreKeyPressed

    private void jtNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNombreKeyTyped
    {//GEN-HEADEREND:event_jtNombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jtNombreKeyTyped

    private void jtMarcaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtMarcaKeyPressed
    {//GEN-HEADEREND:event_jtMarcaKeyPressed
        if (jtMarca.getText().isEmpty() != true)
          {
            Validaciones.enter(this, evt, jtCompra);
          }
    }//GEN-LAST:event_jtMarcaKeyPressed

    private void jtMarcaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtMarcaKeyTyped
    {//GEN-HEADEREND:event_jtMarcaKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jtMarcaKeyTyped

    private void jtCompraKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtCompraKeyPressed
    {//GEN-HEADEREND:event_jtCompraKeyPressed
        if (jtCompra.getText().isEmpty() != true)
          {
            Validaciones.enter(this, evt, jtVenta);
          }
    }//GEN-LAST:event_jtCompraKeyPressed

    private void jtCompraKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtCompraKeyTyped
    {//GEN-HEADEREND:event_jtCompraKeyTyped
        Validaciones.validaFlotantes(evt);
    }//GEN-LAST:event_jtCompraKeyTyped

    private void jtVentaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtVentaKeyPressed
    {//GEN-HEADEREND:event_jtVentaKeyPressed
        if (jtVenta.getText().isEmpty() != true)
          {
            Validaciones.enter(this, evt, jtProveedor);
          }
    }//GEN-LAST:event_jtVentaKeyPressed

    private void jtVentaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtVentaKeyTyped
    {//GEN-HEADEREND:event_jtVentaKeyTyped
        Validaciones.validaFlotantes(evt);
    }//GEN-LAST:event_jtVentaKeyTyped

    private void jtProveedorKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtProveedorKeyPressed
    {//GEN-HEADEREND:event_jtProveedorKeyPressed
        if (jtProveedor.getText().isEmpty() != true)
          {
            Validaciones.enter(this, evt, jtFVenta);
            jcPerec.setEnabled(true);
            CtrlInterfaz.habilita(true, btnBuscar);
          }
    }//GEN-LAST:event_jtProveedorKeyPressed

    private void jtProveedorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtProveedorKeyTyped
    {//GEN-HEADEREND:event_jtProveedorKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jtProveedorKeyTyped

    private void jtFVentaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtFVentaKeyPressed
    {//GEN-HEADEREND:event_jtFVentaKeyPressed
        if (jtFVenta.getText().isEmpty() != true)
          {
            Validaciones.enter(this, evt, evt);
            CtrlInterfaz.habilita(true, btnAceptar);
          }
    }//GEN-LAST:event_jtFVentaKeyPressed

    private void jtFVentaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtFVentaKeyTyped
    {//GEN-HEADEREND:event_jtFVentaKeyTyped
        Validaciones.validaFlotantes(evt);
    }//GEN-LAST:event_jtFVentaKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarActionPerformed
    {//GEN-HEADEREND:event_btnBuscarActionPerformed
        /**
         * Aqui va el metodo para buscar al proveedor
         */
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jcPerecActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcPerecActionPerformed
    {//GEN-HEADEREND:event_jcPerecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPerecActionPerformed

    private void jtFCadKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtFCadKeyPressed
    {//GEN-HEADEREND:event_jtFCadKeyPressed

    }//GEN-LAST:event_jtFCadKeyPressed

    private void jtFCadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtFCadKeyTyped
    {//GEN-HEADEREND:event_jtFCadKeyTyped
        Validaciones.validaFlotantes(evt); // Checar que si sea esta la validacion necesaria para la fecha de caducidad
    }//GEN-LAST:event_jtFCadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
      {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
          {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if ("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          } catch (ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(Agregar_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(Agregar_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(Agregar_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(Agregar_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
          {
            public void run()
              {
                new Agregar_Productos().setVisible(true);
              }
          });
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox jcPerec;
    private javax.swing.JTextField jtCompra;
    private javax.swing.JTextField jtFCad;
    private javax.swing.JTextField jtFVenta;
    private javax.swing.JTextField jtMarca;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtProveedor;
    private javax.swing.JTextField jtVenta;
    // End of variables declaration//GEN-END:variables
}
