package Ventanas;

import clases.ManipulaBD;
import clases.Proveedores;
import java.util.ArrayList;

/**
 *
 * @author Kevin
 */
public class Consultas_Proveedores extends javax.swing.JFrame
  {

    public static ArrayList<Proveedores> provedor;

    /**
     * Creates new form Consultas_Proveedores
     */
    public Consultas_Proveedores()
      {
        initComponents();

        String condicion = "-1";
        provedor = ManipulaBD.ConsultasProveedores("id!=", condicion);
        for (int i = 0; i < provedor.size(); i++)
          {
            TProveedores.setValueAt(provedor.get(i).getNombre(), i, 0);
            TProveedores.setValueAt(provedor.get(i).getApellidoP(), i, 1);
            TProveedores.setValueAt(provedor.get(i).getApellidoM(), i, 2);
            TProveedores.setValueAt(provedor.get(i).getRfc(), i, 3);
            TProveedores.setValueAt(provedor.get(i).getRazon_Social(), i, 4);
            TProveedores.setValueAt(provedor.get(i).getDireccion(), i, 5);
            TProveedores.setValueAt(provedor.get(i).getCp(), i, 6);
            TProveedores.setValueAt(provedor.get(i).getTelefono(), i, 7);
            TProveedores.setValueAt(provedor.get(i).getEmail(), i, 8);

          }

      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        TProveedores = new javax.swing.JTable();
        Bregresar = new javax.swing.JButton();
        BOrdena = new javax.swing.JButton();
        BModifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Nombre", "Apellido P", "Apellido M", "RFC", "Razón Social", "Direccion", "Codigo Postal", "Telefono", "Email", "Estatus"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TProveedores);

        Bregresar.setText("Regresar");
        Bregresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BregresarActionPerformed(evt);
            }
        });

        BOrdena.setText("Ordenar Alafabeticamente");

        BModifica.setText("Modificar");
        BModifica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bregresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BModifica)
                        .addGap(97, 97, 97)
                        .addComponent(BOrdena)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bregresar)
                    .addComponent(BOrdena)
                    .addComponent(BModifica))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BregresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BregresarActionPerformed
    {//GEN-HEADEREND:event_BregresarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_BregresarActionPerformed

    private void BModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BModificaActionPerformed
    {//GEN-HEADEREND:event_BModificaActionPerformed

        for (int i = 0; i < provedor.size(); i++)
          {

            boolean estatus = (boolean) TProveedores.getValueAt(i, 9);
            String estatusS = String.valueOf(estatus);
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "nombre", "'" + TProveedores.getValueAt(i, 0) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "apellidoP", "'" + TProveedores.getValueAt(i, 1) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "apellidoM", "'" + TProveedores.getValueAt(i, 2) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "rfc", "'" + TProveedores.getValueAt(i, 3) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "razon_Social", "'" + TProveedores.getValueAt(i, 4) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "direccion", "'" + TProveedores.getValueAt(i, 5) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "cp", "'" + TProveedores.getValueAt(i, 6) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "telefono", "'" + TProveedores.getValueAt(i, 7) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "email", "'" + TProveedores.getValueAt(i, 8) + "'");
            ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "estatus", "'" + estatusS + "'");

          }
    }//GEN-LAST:event_BModificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
      {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
          {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if ("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          } catch (ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(Consultas_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(Consultas_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(Consultas_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(Consultas_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
          {
            public void run()
              {
                new Consultas_Proveedores().setVisible(true);
              }
          });
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModifica;
    private javax.swing.JButton BOrdena;
    private javax.swing.JButton Bregresar;
    private javax.swing.JTable TProveedores;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
